name="Sandeep working in vegaahi  pvt ltd"
print(name.upper())
print(name.lower())
print(name.capitalize())
print(name.title())
print(name.swapcase())
print(name.find("sai"))
# print(name.index("sai"))
print(name.count("e"))
print(name.split())
print(name.replace("a","@"))
print(name.startswith("Sandeep"))
print(name.endswith("ltd"))
print(name.isalpha())
print(name.isdigit())
print(name.isalnum())
print(name.islower())
# print(name.join(name))
print(name.center(50,"-"))  
print(name.ljust(50,"-"))
print(name.rjust(50,"-"))
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.zfill(50))
print(name.rfind("a"))
print(name.rindex("a"))
print(name[0:10])